---
- name: Run Python scripts with repository from GitHub
  hosts: all
  tasks:
    - name: Install git
      apt:
        name: git
        state: present
      become: yes

    - name: Clone the GitHub repository
      git:
        repo: 'https://github.com/your-repo/your-repo.git'
        dest: /tmp/your-repo
        version: 'main'  # or the branch you need
      become: yes

    - name: Install python3-venv
      apt:
        name: python3-venv
        state: present
      become: yes

    - name: Create virtual environment
      command: python3 -m venv /tmp/venv
      become: yes

    - name: Install Google Cloud Monitoring package
      pip:
        name: google-cloud-monitoring
        virtualenv: /tmp/venv
        state: present
      become: yes

    - name: Run enable.py
      command: /tmp/venv/bin/python /tmp/your-repo/enable.py
      register: result_script1

    - name: Debug output of enable.py
      debug:
        msg: "{{ result_script1.stdout }}"
