---
- name: Run Python scripts with repository from GitHub
  hosts: all
  become: yes
  tasks:
    - name: Install git
      apt:
        name: git
        state: present

    - name: Clone the GitHub repository
      git:
        repo: 'https://github.com/priya135792/gcp-test.git'
        dest: /var/your-repo
        version: 'main'  # or the branch you need

    - name: Install python3 and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Google Cloud Monitoring package
      pip:
        name: google-cloud-monitoring
        state: present

    - name: Check if credentials file exists
      stat:
        path: /var/your-repo/plated-planet-427716-u5-14a35e5f742f.json
      register: credentials_file

    - name: Fail if credentials file not found
      fail:
        msg: "The Google Cloud credentials file was not found at /var/your-repo/plated-planet-427716-u5-14a35e5f742f.json"
      when: not credentials_file.stat.exists

    - name: Write Google Cloud credentials to file
      copy:
        remote_src: yes
        src: /var/your-repo/plated-planet-427716-u5-14a35e5f742f.json
        dest: /var/service-account-key.json
        mode: '0600'

    - name: Run enable.py
      command: python3 /var/your-repo/enable.py
      register: result_script1
      environment:
        GOOGLE_APPLICATION_CREDENTIALS: /var/service-account-key.json

    - name: Debug output of enable.py
      debug:
        msg: "{{ result_script1.stdout }}"

    - name: Debug error output of enable.py
      debug:
        msg: "{{ result_script1.stderr }}"
      when: result_script1.stderr is defined and result_script1.stderr != ""
